services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=password
      - APP_NAME=Laravel
      - APP_ENV=production
      - APP_KEY=base64:cGxlYXNlIGdlbmVyYXRlIHRoaXMga2V5IHVzaW5nIHBocCBhcnRpc2FuIGtleTpnZW5lcmF0ZQ==
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
    volumes:
      - ./storage:/var/www/html/storage
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
