services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './storage:/var/www/html/storage'
    environment:
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379
      AUTORUN_ENABLED: true
